/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.ArbolGnral;
import EDD.HashTable;
import EDD.Lista;
import EDD.Nodo;
import Funciones.CargarArchivo;
import Funciones.FileChooser;
import Funciones.MostrarArbol;
import Modelo.ArbolGenealogico;
import Modelo.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author obelm
 */
public class Iniciar extends javax.swing.JFrame {

    private FileChooser fileChooser = new FileChooser();
    public static ArbolGenealogico arbolGenealogico;

    public Iniciar() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empezar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenidos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        empezar.setText("Empezar");
        empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarActionPerformed(evt);
            }
        });
        jPanel1.add(empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, -1));

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 0, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarActionPerformed
        String rutaArchivo = fileChooser.abrirArchivo(this);
        CargarArchivo cargar = new CargarArchivo();
        cargar.cargar(rutaArchivo);
        if (cargar.getArbolGenealogico() != null) {
            arbolGenealogico = cargar.getArbolGenealogico();
            System.setProperty("org.graphstream.ui", "swing");
            MostrarArbol verArbol = new MostrarArbol(arbolGenealogico.getArbol());
            verArbol.setVisible(true);
            this.dispose();

        } else {
            if (cargar.getErrores() != 0 && cargar.getNombreRepetido() == 0) {
                JOptionPane.showMessageDialog(null, "Error, hay un padre que no esta identificado con su numeral o su mote. Por favor cargue un JSON Correcto.");
            } else if (cargar.getErrores() == 0 && cargar.getNombreRepetido() != 0) {
                JOptionPane.showMessageDialog(null, "Error, hay dos personas con el mismo nombre y numeral o con el mismo mote en generaciones diferentes.");
            } else {
                JOptionPane.showMessageDialog(null, "Error, hay un padre que no esta identificado con su numeral o su mote. Por favor cargue un JSON Correcto.");
                JOptionPane.showMessageDialog(null, "Error, hay dos personas con el mismo nombre y numeral o con el mismo mote en generaciones diferentes.");
            }

        }

        //arbolGenealogico.getHashTable().mostrar();
        //System.out.println("===========================================================");
        //arbolGenealogico.getArbol().mostrarPorNivel();
        //System.out.println(arbolGenealogico.getArbol().maximoNivel());
        //Lista nodosNivel2 = arbolGenealogico.getArbol().obtenerNodosEnNivel(2);
//        Nodo nodo = nodosNivel2.getpFirst();
//        while (nodo != null) {
//            Persona persona = (Persona) nodo.getDato();
//            System.out.println(persona.getNombreCompleto());
//            nodo = nodo.getpNext();
//        }

    }//GEN-LAST:event_empezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
