/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.MostrarArbol;
import Funciones.Validar;
import static Interfaces.Iniciar.arbolGenealogico;

/**
 *
 * @author obelm
 */
public class Menu extends javax.swing.JFrame {

    public static Validar validar = new Validar();
    
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.nombreCasaSist.setText(arbolGenealogico.getNombreLinaje());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreCasaSist = new javax.swing.JLabel();
        buscarNombreBoton = new javax.swing.JButton();
        buscarTituloBoton = new javax.swing.JButton();
        ListarGeneracion = new javax.swing.JButton();
        mostrarAntepasados = new javax.swing.JButton();
        CargarNuevoLinaje = new javax.swing.JButton();
        MostrarArbol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        nombreCasaSist.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        nombreCasaSist.setText("NOMBRE DE LA CASA");
        jPanel1.add(nombreCasaSist, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        buscarNombreBoton.setText("Buscar Por Nombre");
        buscarNombreBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreBotonActionPerformed(evt);
            }
        });
        jPanel1.add(buscarNombreBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        buscarTituloBoton.setText("Buscar por Titulo");
        buscarTituloBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTituloBotonActionPerformed(evt);
            }
        });
        jPanel1.add(buscarTituloBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        ListarGeneracion.setText("Listar Generacion");
        ListarGeneracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarGeneracionActionPerformed(evt);
            }
        });
        jPanel1.add(ListarGeneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 130, -1));

        mostrarAntepasados.setText("Mostrar Antepasados");
        mostrarAntepasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAntepasadosActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarAntepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, -1));

        CargarNuevoLinaje.setText("Cargar Nuevo Linaje");
        jPanel1.add(CargarNuevoLinaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 150, -1));

        MostrarArbol.setText("Mostrar Arbol");
        MostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarArbolActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarNombreBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreBotonActionPerformed
        BuscarNombre v1 = new BuscarNombre();
        this.dispose();
    }//GEN-LAST:event_buscarNombreBotonActionPerformed

    private void buscarTituloBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTituloBotonActionPerformed
        BuscarTitulo v2 = new BuscarTitulo();
        this.dispose();
    }//GEN-LAST:event_buscarTituloBotonActionPerformed

    private void ListarGeneracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarGeneracionActionPerformed
        ListaGeneracion v3 = new ListaGeneracion();
        this.dispose();
    }//GEN-LAST:event_ListarGeneracionActionPerformed

    private void MostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarArbolActionPerformed
        System.setProperty("org.graphstream.ui", "swing");
        MostrarArbol verArbol = new MostrarArbol(arbolGenealogico.getArbol());
        verArbol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MostrarArbolActionPerformed

    private void mostrarAntepasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAntepasadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarAntepasadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarNuevoLinaje;
    private javax.swing.JButton ListarGeneracion;
    private javax.swing.JButton MostrarArbol;
    private javax.swing.JButton buscarNombreBoton;
    private javax.swing.JButton buscarTituloBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarAntepasados;
    private javax.swing.JLabel nombreCasaSist;
    // End of variables declaration//GEN-END:variables
}
