/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.CargarArchivo;
import Funciones.FileChooser;
import Funciones.MostrarArbol;
import Funciones.MostrarImagen;
import Funciones.Validar;
import static Interfaces.Iniciar.arbolGenealogico;
import javax.swing.JOptionPane;

/**
 *
 * @author obelm
 */
public class Menu extends javax.swing.JFrame {

    public static Validar validar = new Validar();

    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.nombreCasaSist.setText(arbolGenealogico.getNombreLinaje());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreCasaSist = new javax.swing.JLabel();
        buscarNombreBoton = new javax.swing.JButton();
        buscarTituloBoton = new javax.swing.JButton();
        ListarGeneracion = new javax.swing.JButton();
        mostrarAntepasados = new javax.swing.JButton();
        CargarNuevoLinaje = new javax.swing.JButton();
        MostrarArbol = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        nombreCasaSist.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        nombreCasaSist.setText("1");
        jPanel1.add(nombreCasaSist, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        buscarNombreBoton.setText("Buscar Por Nombre");
        buscarNombreBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreBotonActionPerformed(evt);
            }
        });
        jPanel1.add(buscarNombreBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, -1));

        buscarTituloBoton.setText("Buscar por Titulo");
        buscarTituloBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTituloBotonActionPerformed(evt);
            }
        });
        jPanel1.add(buscarTituloBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 190, 20));

        ListarGeneracion.setText("Listar Generacion");
        ListarGeneracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarGeneracionActionPerformed(evt);
            }
        });
        jPanel1.add(ListarGeneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 190, -1));

        mostrarAntepasados.setText("Mostrar Antepasados");
        mostrarAntepasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAntepasadosActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarAntepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, -1));

        CargarNuevoLinaje.setText("Cargar Nuevo Linaje");
        CargarNuevoLinaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarNuevoLinajeActionPerformed(evt);
            }
        });
        jPanel1.add(CargarNuevoLinaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 190, -1));

        MostrarArbol.setText("Mostrar Arbol");
        MostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarArbolActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, -1));

        jButton1.setText("Mostrar Diagrama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 180, -1));

        jButton2.setText("Ver Relaciones Cercanas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.0.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarNombreBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreBotonActionPerformed
        BuscarNombre v1 = new BuscarNombre();
        this.dispose();
    }//GEN-LAST:event_buscarNombreBotonActionPerformed

    private void buscarTituloBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTituloBotonActionPerformed
        BuscarTitulo v2 = new BuscarTitulo();
        this.dispose();
    }//GEN-LAST:event_buscarTituloBotonActionPerformed

    private void ListarGeneracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarGeneracionActionPerformed
        ListaGeneracion v3 = new ListaGeneracion();
        this.dispose();
    }//GEN-LAST:event_ListarGeneracionActionPerformed

    private void MostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarArbolActionPerformed
        System.setProperty("org.graphstream.ui", "swing");
        MostrarArbol verArbol = new MostrarArbol(arbolGenealogico.getArbol());
        verArbol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MostrarArbolActionPerformed

    private void mostrarAntepasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAntepasadosActionPerformed
        VerAntepasados v4 = new VerAntepasados();
        this.dispose();
    }//GEN-LAST:event_mostrarAntepasadosActionPerformed

    private void CargarNuevoLinajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarNuevoLinajeActionPerformed
        FileChooser fileChooser = new FileChooser();
        String rutaArchivo = fileChooser.abrirArchivo(this);
        CargarArchivo cargar = new CargarArchivo();
        cargar.cargar(rutaArchivo);
        if (cargar.getArbolGenealogico() != null) {
            arbolGenealogico = cargar.getArbolGenealogico();
            System.setProperty("org.graphstream.ui", "swing");
            MostrarArbol verArbol = new MostrarArbol(arbolGenealogico.getArbol());
            verArbol.setVisible(true);
            this.dispose();

        } else {
            if (cargar.getErrores() != 0 && cargar.getNombreRepetido() == 0) {
                JOptionPane.showMessageDialog(null, "Error, hay un padre que no esta identificado con su numeral o su mote. Por favor cargue un JSON Correcto.");
            } else if (cargar.getErrores() == 0 && cargar.getNombreRepetido() != 0) {
                JOptionPane.showMessageDialog(null, "Error, hay dos personas con el mismo nombre y numeral o con el mismo mote en generaciones diferentes.");
            } else {
                JOptionPane.showMessageDialog(null, "Error, hay un padre que no esta identificado con su numeral o su mote. Por favor cargue un JSON Correcto.");
                JOptionPane.showMessageDialog(null, "Error, hay dos personas con el mismo nombre y numeral o con el mismo mote en generaciones diferentes.");
            }

        }
    }//GEN-LAST:event_CargarNuevoLinajeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MostrarImagen ventana = new MostrarImagen("DiagramaClases.jpg");
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VerFamiliaCercana v5 = new VerFamiliaCercana();
        this.dispose();
              
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarNuevoLinaje;
    private javax.swing.JButton ListarGeneracion;
    private javax.swing.JButton MostrarArbol;
    private javax.swing.JButton buscarNombreBoton;
    private javax.swing.JButton buscarTituloBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarAntepasados;
    private javax.swing.JLabel nombreCasaSist;
    // End of variables declaration//GEN-END:variables
}
